export const notification = {
    GET_FAIL_VI: 'Lấy danh sách thất bại!',
    GET_FAIL_EN: 'Get list failed!',
    CREATE_SUCCESS_VI: 'Tạo mới thành công!',
    CREATE_SUCCESS_EN: 'Create success!',
    CREATE_FAIL_VI: 'Tạo mới thất bại!',
    CREATE_FAIL_EN: 'Create failed!',
    UPDATE_SUCCESS_VI: 'Cập nhật thành công!',
    UPDATE_SUCCESS_EN: 'Update success!',
    UPDATE_FAIL_VI: 'Cập nhật thất bại!',
    UPDATE_FAIL_EN: 'Update failed!',
    UPDATE_PASS_SUCCESS_VI: 'Đặt lại mật khẩu thành công!',
    UPDATE_PASS_SUCCESS_EN: 'Reset password success!',
    UPDATE_PASS_FAIL_VI: 'Đặt lại mật khẩu thất bại!',
    UPDATE_PASS_FAIL_EN: 'Reset password failed!',
    DELETE_SUCCESS_VI: 'Xóa thành công!',
    DELETE_SUCCESS_EN: 'Delete success!',
    DELETE_FAIL_VI: 'Xóa thất bại!',
    DELETE_FAIL_EN: 'Delete failed!',
    RESEND_SUCCESS_VI: 'Gửi lại thành công!',
    RESEND_SUCCESS_EN: 'Resend success!',
    RESEND_FAIL_VI: 'Gửi lại thất bại!',
    RESEND_FAIL_EN: 'Resend failed!',
    SUCCESS_VI: 'Thành công!',
    SUCCESS_EN: 'Success!',
    FAIL_VI: 'Thất bại!',
    FAIL_EN: 'Failed!',
    MESSAGE_ERROR_VI: 'Có lỗi xảy ra!',
    MESSAGE_ERROR_EN: 'Error occurs!',
    MESSAGE_ERROR_SEARCH_VI: 'Không tìm thấy tài liệu!',
    MESSAGE_ERROR_SEARCH_EN: 'Document not found!',
    MESSAGE_ERROR_LOAD: 'Có lỗi xảy ra, bạn cần tải lại trang web!',
    MESSAGE_VALIDATE: 'Kiểm tra lại dữ liệu nhập!',
    SEND_EMAIL_SUCCESS: 'Gửi email thành công!',
    SEND_EMAIL_FAIL: 'Gửi email thất bại!',
    CHECK_SUCCESS: 'Kiểm tra thành công!',
    CHECK_FAIL: 'Kiểm tra thất bại!',
    NOTIFY_READ: "Đọc thông báo!",
    NOTIFY_DELETE: "Gỡ thông báo!",
    FILE_DOES_NOT_EXIST: "File không tồn tại!",
    FILE_UPLOAD_SUCCESS: "Tải lên file thành công!",
    CTS_NOT_FOUND: "Không tìm thấy chứng thư số!"
}
