export const urlApi = {
    URL_VIEW_DIGITAL_CERTIFICATE: 'crm/cau-hinh-chung-thu-so/getFile',
    URL_VIEW_SUBMISSION: 'crm/tai-lieu-trinh-ky/getFile',
    URL_VIEW_CONTRACT: 'crm/quan-ly-hop-dong/getFile',
    URL_GET_USER_INFO: 'crm/tai-khoan/getUserInfo',
    URL_FOLDER_DOCUMENT: 'crm/thu-muc-tai-lieu/download',
    URL_PERSONAL_DOCUMENT: 'crm/tai-lieu-ca-nhan/getFile',
    PATH_URL_PERSONAL_DOCUMENT: 'tai-lieu-ca-nhan',
    URL_GET_CERT_PLUGIN: 'cybercrm/getcert',
    URL_SIGN_PDF_SERIAL_PLUGIN: 'cybersign/signPdfSerial',
    URL_SIGN_PDF_PLUGIN: 'cybersign/signpdf',
    URL_DOWNLOAD_ALL_FILE_SUBMISSION: 'crm/tai-lieu-trinh-ky/downloadAllFile',
    URL_DOWNLOAD_ALL_FILE_SUBMISSION_REFUSE: 'crm/trinh-ky-da-tu-choi/downloadAllFile',
    URL_DOWNLOAD_ALL_FILE_CONTRACT: 'crm/quan-ly-hop-dong/downloadAllFile',
    URL_CUSTOMER_DOWNLOAD_ALL_FILE_CONTRACT: 'client/hop-dong-khach-hang/downloadAllFile',
    URL_CUSTOMER_DOWNLOAD_ALL_FILE_SUBMISSION: 'client/trinh-ky-khach-hang/downloadAllFile',
    URL_VIEW_CONTRACT_CLIENT: 'client/hop-dong-khach-hang/getFile',
    URL_VIEW_SUBMISSION_CLIENT: 'client/trinh-ky-khach-hang/getFile',
    URL_CUSTOMER_DOWNLOAD_CONTRACT_DUPLICATE: 'client/hop-dong-khach-hang/downloadFileDuplicate',
    URL_CUSTOMER_DOWNLOAD_SUBMISSION_DUPLICATE: 'client/trinh-ky-khach-hang/downloadFileDuplicate',
    URL_DOWNLOAD: 'client/quan-ly-phan-mem/download',
    URL_DOC_SENT: 'crm/tai-lieu-di/getFileContent',
    URL_DOC_COME: 'crm/tai-lieu-den/getFileContent',
}
